/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Sseotdabwa API
 * Sseotdabwa Project
 * OpenAPI spec version: v1.0.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  AppleLoginRequest,
  GoogleLoginRequest,
  KakaoLoginRequest,
  TokenRefreshRequest,
} from ".././model";

import { customFetch } from ".././custom-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * JWT Access Token 갱신 API입니다.

Refresh Token으로 새로운 Access Token을 발급받습니다.
Access Token 만료 시(1시간) 이 API를 호출하세요.

 * @summary 토큰 갱신
 */
export type refreshTokenResponse200 = {
  data: Blob;
  status: 200;
};

export type refreshTokenResponse401 = {
  data: Blob;
  status: 401;
};

export type refreshTokenResponseSuccess = refreshTokenResponse200 & {
  headers: Headers;
};
export type refreshTokenResponseError = refreshTokenResponse401 & {
  headers: Headers;
};

export type refreshTokenResponse =
  | refreshTokenResponseSuccess
  | refreshTokenResponseError;

export const getRefreshTokenUrl = () => {
  return `/api/v1/auth/refresh`;
};

export const refreshToken = async (
  tokenRefreshRequest: TokenRefreshRequest,
  options?: RequestInit,
): Promise<refreshTokenResponse> => {
  return customFetch<refreshTokenResponse>(getRefreshTokenUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(tokenRefreshRequest),
  });
};

export const getRefreshTokenMutationOptions = <
  TError = Blob,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof refreshToken>>,
    TError,
    { data: TokenRefreshRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof refreshToken>>,
  TError,
  { data: TokenRefreshRequest },
  TContext
> => {
  const mutationKey = ["refreshToken"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof refreshToken>>,
    { data: TokenRefreshRequest }
  > = (props) => {
    const { data } = props ?? {};

    return refreshToken(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RefreshTokenMutationResult = NonNullable<
  Awaited<ReturnType<typeof refreshToken>>
>;
export type RefreshTokenMutationBody = TokenRefreshRequest;
export type RefreshTokenMutationError = Blob;

/**
 * @summary 토큰 갱신
 */
export const useRefreshToken = <TError = Blob, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof refreshToken>>,
      TError,
      { data: TokenRefreshRequest },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof refreshToken>>,
  TError,
  { data: TokenRefreshRequest },
  TContext
> => {
  return useMutation(getRefreshTokenMutationOptions(options), queryClient);
};
/**
 * 카카오 소셜 로그인 API입니다.

클라이언트(Android/iOS/Web)에서 카카오 SDK로 발급받은 Access Token을 전달하면,
서버에서 카카오 API를 통해 사용자 정보를 조회하고 JWT 토큰을 발급합니다.

- 신규 사용자: 자동 회원가입 후 토큰 발급
- 기존 사용자: 프로필 정보 업데이트 후 토큰 발급

 * @summary [카카오] 소셜 로그인
 */
export type loginWithKakaoResponse200 = {
  data: Blob;
  status: 200;
};

export type loginWithKakaoResponse401 = {
  data: Blob;
  status: 401;
};

export type loginWithKakaoResponse502 = {
  data: Blob;
  status: 502;
};

export type loginWithKakaoResponseSuccess = loginWithKakaoResponse200 & {
  headers: Headers;
};
export type loginWithKakaoResponseError = (
  | loginWithKakaoResponse401
  | loginWithKakaoResponse502
) & {
  headers: Headers;
};

export type loginWithKakaoResponse =
  | loginWithKakaoResponseSuccess
  | loginWithKakaoResponseError;

export const getLoginWithKakaoUrl = () => {
  return `/api/v1/auth/kakao/login`;
};

export const loginWithKakao = async (
  kakaoLoginRequest: KakaoLoginRequest,
  options?: RequestInit,
): Promise<loginWithKakaoResponse> => {
  return customFetch<loginWithKakaoResponse>(getLoginWithKakaoUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(kakaoLoginRequest),
  });
};

export const getLoginWithKakaoMutationOptions = <
  TError = Blob,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginWithKakao>>,
    TError,
    { data: KakaoLoginRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginWithKakao>>,
  TError,
  { data: KakaoLoginRequest },
  TContext
> => {
  const mutationKey = ["loginWithKakao"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginWithKakao>>,
    { data: KakaoLoginRequest }
  > = (props) => {
    const { data } = props ?? {};

    return loginWithKakao(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginWithKakaoMutationResult = NonNullable<
  Awaited<ReturnType<typeof loginWithKakao>>
>;
export type LoginWithKakaoMutationBody = KakaoLoginRequest;
export type LoginWithKakaoMutationError = Blob;

/**
 * @summary [카카오] 소셜 로그인
 */
export const useLoginWithKakao = <TError = Blob, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof loginWithKakao>>,
      TError,
      { data: KakaoLoginRequest },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof loginWithKakao>>,
  TError,
  { data: KakaoLoginRequest },
  TContext
> => {
  return useMutation(getLoginWithKakaoMutationOptions(options), queryClient);
};
/**
 * Google 소셜 로그인 API입니다.

클라이언트(iOS/Android/Web)에서 Google SDK로 발급받은 ID Token을 전달하면,
서버에서 Google 공개키로 토큰을 검증하고 JWT 토큰을 발급합니다.

- 신규 사용자: 자동 회원가입 후 토큰 발급 (랜덤 닉네임/프로필 이미지 부여)
- 기존 사용자: 토큰 발급

 * @summary [Google] 소셜 로그인
 */
export type loginWithGoogleResponse200 = {
  data: Blob;
  status: 200;
};

export type loginWithGoogleResponse401 = {
  data: Blob;
  status: 401;
};

export type loginWithGoogleResponse502 = {
  data: Blob;
  status: 502;
};

export type loginWithGoogleResponseSuccess = loginWithGoogleResponse200 & {
  headers: Headers;
};
export type loginWithGoogleResponseError = (
  | loginWithGoogleResponse401
  | loginWithGoogleResponse502
) & {
  headers: Headers;
};

export type loginWithGoogleResponse =
  | loginWithGoogleResponseSuccess
  | loginWithGoogleResponseError;

export const getLoginWithGoogleUrl = () => {
  return `/api/v1/auth/google/login`;
};

export const loginWithGoogle = async (
  googleLoginRequest: GoogleLoginRequest,
  options?: RequestInit,
): Promise<loginWithGoogleResponse> => {
  return customFetch<loginWithGoogleResponse>(getLoginWithGoogleUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(googleLoginRequest),
  });
};

export const getLoginWithGoogleMutationOptions = <
  TError = Blob,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginWithGoogle>>,
    TError,
    { data: GoogleLoginRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginWithGoogle>>,
  TError,
  { data: GoogleLoginRequest },
  TContext
> => {
  const mutationKey = ["loginWithGoogle"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginWithGoogle>>,
    { data: GoogleLoginRequest }
  > = (props) => {
    const { data } = props ?? {};

    return loginWithGoogle(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginWithGoogleMutationResult = NonNullable<
  Awaited<ReturnType<typeof loginWithGoogle>>
>;
export type LoginWithGoogleMutationBody = GoogleLoginRequest;
export type LoginWithGoogleMutationError = Blob;

/**
 * @summary [Google] 소셜 로그인
 */
export const useLoginWithGoogle = <TError = Blob, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof loginWithGoogle>>,
      TError,
      { data: GoogleLoginRequest },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof loginWithGoogle>>,
  TError,
  { data: GoogleLoginRequest },
  TContext
> => {
  return useMutation(getLoginWithGoogleMutationOptions(options), queryClient);
};
/**
 * Apple 소셜 로그인 API입니다.

클라이언트(iOS/Web)에서 Apple SDK로 발급받은 Authorization Code를 전달하면,
서버에서 Apple Token API를 호출하여 사용자를 검증하고 JWT 토큰을 발급합니다.

- 신규 사용자: 자동 회원가입 후 토큰 발급 (랜덤 닉네임/프로필 이미지 부여)
- 기존 사용자: 토큰 발급

**redirectUri 파라미터:**
- iOS 앱 (ASAuthorizationAppleIDProvider): 생략 가능
- Web: 필수 (초기 인증 요청에서 사용한 redirect_uri와 동일한 값)

 * @summary [Apple] 소셜 로그인
 */
export type loginWithAppleResponse200 = {
  data: Blob;
  status: 200;
};

export type loginWithAppleResponse401 = {
  data: Blob;
  status: 401;
};

export type loginWithAppleResponse502 = {
  data: Blob;
  status: 502;
};

export type loginWithAppleResponseSuccess = loginWithAppleResponse200 & {
  headers: Headers;
};
export type loginWithAppleResponseError = (
  | loginWithAppleResponse401
  | loginWithAppleResponse502
) & {
  headers: Headers;
};

export type loginWithAppleResponse =
  | loginWithAppleResponseSuccess
  | loginWithAppleResponseError;

export const getLoginWithAppleUrl = () => {
  return `/api/v1/auth/apple/login`;
};

export const loginWithApple = async (
  appleLoginRequest: AppleLoginRequest,
  options?: RequestInit,
): Promise<loginWithAppleResponse> => {
  return customFetch<loginWithAppleResponse>(getLoginWithAppleUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(appleLoginRequest),
  });
};

export const getLoginWithAppleMutationOptions = <
  TError = Blob,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginWithApple>>,
    TError,
    { data: AppleLoginRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginWithApple>>,
  TError,
  { data: AppleLoginRequest },
  TContext
> => {
  const mutationKey = ["loginWithApple"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginWithApple>>,
    { data: AppleLoginRequest }
  > = (props) => {
    const { data } = props ?? {};

    return loginWithApple(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginWithAppleMutationResult = NonNullable<
  Awaited<ReturnType<typeof loginWithApple>>
>;
export type LoginWithAppleMutationBody = AppleLoginRequest;
export type LoginWithAppleMutationError = Blob;

/**
 * @summary [Apple] 소셜 로그인
 */
export const useLoginWithApple = <TError = Blob, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof loginWithApple>>,
      TError,
      { data: AppleLoginRequest },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof loginWithApple>>,
  TError,
  { data: AppleLoginRequest },
  TContext
> => {
  return useMutation(getLoginWithAppleMutationOptions(options), queryClient);
};
