/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Sseotdabwa API
 * Sseotdabwa Project
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  FcmTokenRequest
} from '.././model';

import { customFetch } from '.././custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 현재 로그인한 사용자의 FCM 토큰을 저장(업데이트)합니다.
 * @summary FCM 토큰 등록/갱신
 */
export type updateFcmTokenResponse200 = {
  data: Blob
  status: 200
}

export type updateFcmTokenResponse401 = {
  data: Blob
  status: 401
}
    
export type updateFcmTokenResponseSuccess = (updateFcmTokenResponse200) & {
  headers: Headers;
};
export type updateFcmTokenResponseError = (updateFcmTokenResponse401) & {
  headers: Headers;
};

export type updateFcmTokenResponse = (updateFcmTokenResponseSuccess | updateFcmTokenResponseError)

export const getUpdateFcmTokenUrl = () => {


  

  return `/api/v1/users/fcm`
}

export const updateFcmToken = async (fcmTokenRequest: FcmTokenRequest, options?: RequestInit): Promise<updateFcmTokenResponse> => {
  
  return customFetch<updateFcmTokenResponse>(getUpdateFcmTokenUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      fcmTokenRequest,)
  }
);}




export const getUpdateFcmTokenMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFcmToken>>, TError,{data: FcmTokenRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateFcmToken>>, TError,{data: FcmTokenRequest}, TContext> => {

const mutationKey = ['updateFcmToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateFcmToken>>, {data: FcmTokenRequest}> = (props) => {
          const {data} = props ?? {};

          return  updateFcmToken(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateFcmTokenMutationResult = NonNullable<Awaited<ReturnType<typeof updateFcmToken>>>
    export type UpdateFcmTokenMutationBody = FcmTokenRequest
    export type UpdateFcmTokenMutationError = Blob

    /**
 * @summary FCM 토큰 등록/갱신
 */
export const useUpdateFcmToken = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFcmToken>>, TError,{data: FcmTokenRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateFcmToken>>,
        TError,
        {data: FcmTokenRequest},
        TContext
      > => {
      return useMutation(getUpdateFcmTokenMutationOptions(options), queryClient);
    }
    /**
 * 현재 로그인한 사용자의 정보를 조회합니다.
 * @summary 내 정보 조회
 */
export type getMyInfoResponse200 = {
  data: Blob
  status: 200
}

export type getMyInfoResponse401 = {
  data: Blob
  status: 401
}
    
export type getMyInfoResponseSuccess = (getMyInfoResponse200) & {
  headers: Headers;
};
export type getMyInfoResponseError = (getMyInfoResponse401) & {
  headers: Headers;
};

export type getMyInfoResponse = (getMyInfoResponseSuccess | getMyInfoResponseError)

export const getGetMyInfoUrl = () => {


  

  return `/api/v1/users/me`
}

export const getMyInfo = async ( options?: RequestInit): Promise<getMyInfoResponse> => {
  
  return customFetch<getMyInfoResponse>(getGetMyInfoUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMyInfoQueryKey = () => {
    return [
    `/api/v1/users/me`
    ] as const;
    }

    
export const getGetMyInfoQueryOptions = <TData = Awaited<ReturnType<typeof getMyInfo>>, TError = Blob>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyInfoQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyInfo>>> = ({ signal }) => getMyInfo({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getMyInfo>>>
export type GetMyInfoQueryError = Blob


export function useGetMyInfo<TData = Awaited<ReturnType<typeof getMyInfo>>, TError = Blob>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyInfo>>,
          TError,
          Awaited<ReturnType<typeof getMyInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyInfo<TData = Awaited<ReturnType<typeof getMyInfo>>, TError = Blob>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyInfo>>,
          TError,
          Awaited<ReturnType<typeof getMyInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyInfo<TData = Awaited<ReturnType<typeof getMyInfo>>, TError = Blob>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 내 정보 조회
 */

export function useGetMyInfo<TData = Awaited<ReturnType<typeof getMyInfo>>, TError = Blob>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 현재 로그인한 사용자의 계정을 삭제합니다.
 * @summary 회원 탈퇴
 */
export type withdrawResponse200 = {
  data: Blob
  status: 200
}

export type withdrawResponse401 = {
  data: Blob
  status: 401
}
    
export type withdrawResponseSuccess = (withdrawResponse200) & {
  headers: Headers;
};
export type withdrawResponseError = (withdrawResponse401) & {
  headers: Headers;
};

export type withdrawResponse = (withdrawResponseSuccess | withdrawResponseError)

export const getWithdrawUrl = () => {


  

  return `/api/v1/users/me`
}

export const withdraw = async ( options?: RequestInit): Promise<withdrawResponse> => {
  
  return customFetch<withdrawResponse>(getWithdrawUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getWithdrawMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof withdraw>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof withdraw>>, TError,void, TContext> => {

const mutationKey = ['withdraw'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof withdraw>>, void> = () => {
          

          return  withdraw(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type WithdrawMutationResult = NonNullable<Awaited<ReturnType<typeof withdraw>>>
    
    export type WithdrawMutationError = Blob

    /**
 * @summary 회원 탈퇴
 */
export const useWithdraw = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof withdraw>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof withdraw>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getWithdrawMutationOptions(options), queryClient);
    }
    /**
 * 현재 로그인한 사용자가 작성한 피드 목록을 조회합니다.
 * @summary 내가 작성한 피드 조회
 */
export type getMyFeedsResponse200 = {
  data: Blob
  status: 200
}

export type getMyFeedsResponse401 = {
  data: Blob
  status: 401
}
    
export type getMyFeedsResponseSuccess = (getMyFeedsResponse200) & {
  headers: Headers;
};
export type getMyFeedsResponseError = (getMyFeedsResponse401) & {
  headers: Headers;
};

export type getMyFeedsResponse = (getMyFeedsResponseSuccess | getMyFeedsResponseError)

export const getGetMyFeedsUrl = () => {


  

  return `/api/v1/users/me/feeds`
}

export const getMyFeeds = async ( options?: RequestInit): Promise<getMyFeedsResponse> => {
  
  return customFetch<getMyFeedsResponse>(getGetMyFeedsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMyFeedsQueryKey = () => {
    return [
    `/api/v1/users/me/feeds`
    ] as const;
    }

    
export const getGetMyFeedsQueryOptions = <TData = Awaited<ReturnType<typeof getMyFeeds>>, TError = Blob>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyFeeds>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyFeedsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyFeeds>>> = ({ signal }) => getMyFeeds({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyFeeds>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyFeedsQueryResult = NonNullable<Awaited<ReturnType<typeof getMyFeeds>>>
export type GetMyFeedsQueryError = Blob


export function useGetMyFeeds<TData = Awaited<ReturnType<typeof getMyFeeds>>, TError = Blob>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyFeeds>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyFeeds>>,
          TError,
          Awaited<ReturnType<typeof getMyFeeds>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyFeeds<TData = Awaited<ReturnType<typeof getMyFeeds>>, TError = Blob>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyFeeds>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyFeeds>>,
          TError,
          Awaited<ReturnType<typeof getMyFeeds>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyFeeds<TData = Awaited<ReturnType<typeof getMyFeeds>>, TError = Blob>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyFeeds>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 내가 작성한 피드 조회
 */

export function useGetMyFeeds<TData = Awaited<ReturnType<typeof getMyFeeds>>, TError = Blob>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyFeeds>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyFeedsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




