/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Sseotdabwa API
 * Sseotdabwa Project
 * OpenAPI spec version: v1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from '.././custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 현재 로그인한 사용자의 정보를 조회합니다.
 * @summary 내 정보 조회
 */
export type getMyInfoResponse200 = {
  data: Blob
  status: 200
}

export type getMyInfoResponse401 = {
  data: Blob
  status: 401
}
    
export type getMyInfoResponseSuccess = (getMyInfoResponse200) & {
  headers: Headers;
};
export type getMyInfoResponseError = (getMyInfoResponse401) & {
  headers: Headers;
};

export type getMyInfoResponse = (getMyInfoResponseSuccess | getMyInfoResponseError)

export const getGetMyInfoUrl = () => {


  

  return `/api/v1/users/me`
}

export const getMyInfo = async ( options?: RequestInit): Promise<getMyInfoResponse> => {
  
  return customFetch<getMyInfoResponse>(getGetMyInfoUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMyInfoQueryKey = () => {
    return [
    `/api/v1/users/me`
    ] as const;
    }

    
export const getGetMyInfoQueryOptions = <TData = Awaited<ReturnType<typeof getMyInfo>>, TError = Blob>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyInfoQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyInfo>>> = ({ signal }) => getMyInfo({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getMyInfo>>>
export type GetMyInfoQueryError = Blob


export function useGetMyInfo<TData = Awaited<ReturnType<typeof getMyInfo>>, TError = Blob>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyInfo>>,
          TError,
          Awaited<ReturnType<typeof getMyInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyInfo<TData = Awaited<ReturnType<typeof getMyInfo>>, TError = Blob>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyInfo>>,
          TError,
          Awaited<ReturnType<typeof getMyInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyInfo<TData = Awaited<ReturnType<typeof getMyInfo>>, TError = Blob>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 내 정보 조회
 */

export function useGetMyInfo<TData = Awaited<ReturnType<typeof getMyInfo>>, TError = Blob>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




