/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Sseotdabwa API
 * Sseotdabwa Project
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  FeedCreateRequest
} from '.././model';

import { customFetch } from '.././custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 전체 피드 리스트를 조회합니다. 비로그인 유저도 접근 가능합니다.
 * @summary 피드 리스트 조회
 */
export type getFeedListResponse200 = {
  data: Blob
  status: 200
}
    
export type getFeedListResponseSuccess = (getFeedListResponse200) & {
  headers: Headers;
};
;

export type getFeedListResponse = (getFeedListResponseSuccess)

export const getGetFeedListUrl = () => {


  

  return `/api/v1/feeds`
}

export const getFeedList = async ( options?: RequestInit): Promise<getFeedListResponse> => {
  
  return customFetch<getFeedListResponse>(getGetFeedListUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetFeedListQueryKey = () => {
    return [
    `/api/v1/feeds`
    ] as const;
    }

    
export const getGetFeedListQueryOptions = <TData = Awaited<ReturnType<typeof getFeedList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFeedListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFeedList>>> = ({ signal }) => getFeedList({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFeedList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFeedListQueryResult = NonNullable<Awaited<ReturnType<typeof getFeedList>>>
export type GetFeedListQueryError = unknown


export function useGetFeedList<TData = Awaited<ReturnType<typeof getFeedList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeedList>>,
          TError,
          Awaited<ReturnType<typeof getFeedList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFeedList<TData = Awaited<ReturnType<typeof getFeedList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeedList>>,
          TError,
          Awaited<ReturnType<typeof getFeedList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFeedList<TData = Awaited<ReturnType<typeof getFeedList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 피드 리스트 조회
 */

export function useGetFeedList<TData = Awaited<ReturnType<typeof getFeedList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFeedListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 피드(투표) 등록 API입니다.

- 필수 입력: category, price, s3ObjectKey, imageWidth, imageHeight
- 이미지는 Presigned URL 업로드 방식이며, 현재 API는 업로드 완료된 s3ObjectKey만 받습니다.

 * @summary 피드(투표) 등록
 */
export type createFeedResponse201 = {
  data: Blob
  status: 201
}

export type createFeedResponse400 = {
  data: Blob
  status: 400
}

export type createFeedResponse401 = {
  data: Blob
  status: 401
}
    
export type createFeedResponseSuccess = (createFeedResponse201) & {
  headers: Headers;
};
export type createFeedResponseError = (createFeedResponse400 | createFeedResponse401) & {
  headers: Headers;
};

export type createFeedResponse = (createFeedResponseSuccess | createFeedResponseError)

export const getCreateFeedUrl = () => {


  

  return `/api/v1/feeds`
}

export const createFeed = async (feedCreateRequest: FeedCreateRequest, options?: RequestInit): Promise<createFeedResponse> => {
  
  return customFetch<createFeedResponse>(getCreateFeedUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      feedCreateRequest,)
  }
);}




export const getCreateFeedMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFeed>>, TError,{data: FeedCreateRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createFeed>>, TError,{data: FeedCreateRequest}, TContext> => {

const mutationKey = ['createFeed'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createFeed>>, {data: FeedCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  createFeed(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateFeedMutationResult = NonNullable<Awaited<ReturnType<typeof createFeed>>>
    export type CreateFeedMutationBody = FeedCreateRequest
    export type CreateFeedMutationError = Blob

    /**
 * @summary 피드(투표) 등록
 */
export const useCreateFeed = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFeed>>, TError,{data: FeedCreateRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createFeed>>,
        TError,
        {data: FeedCreateRequest},
        TContext
      > => {
      return useMutation(getCreateFeedMutationOptions(options), queryClient);
    }
    /**
 * 피드를 신고합니다. 본인의 피드는 신고할 수 없습니다.
 * @summary 피드 신고
 */
export type reportFeedResponse200 = {
  data: Blob
  status: 200
}

export type reportFeedResponse400 = {
  data: Blob
  status: 400
}

export type reportFeedResponse401 = {
  data: Blob
  status: 401
}

export type reportFeedResponse404 = {
  data: Blob
  status: 404
}
    
export type reportFeedResponseSuccess = (reportFeedResponse200) & {
  headers: Headers;
};
export type reportFeedResponseError = (reportFeedResponse400 | reportFeedResponse401 | reportFeedResponse404) & {
  headers: Headers;
};

export type reportFeedResponse = (reportFeedResponseSuccess | reportFeedResponseError)

export const getReportFeedUrl = (feedId: number,) => {


  

  return `/api/v1/feeds/${feedId}/report`
}

export const reportFeed = async (feedId: number, options?: RequestInit): Promise<reportFeedResponse> => {
  
  return customFetch<reportFeedResponse>(getReportFeedUrl(feedId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getReportFeedMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reportFeed>>, TError,{feedId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof reportFeed>>, TError,{feedId: number}, TContext> => {

const mutationKey = ['reportFeed'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reportFeed>>, {feedId: number}> = (props) => {
          const {feedId} = props ?? {};

          return  reportFeed(feedId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ReportFeedMutationResult = NonNullable<Awaited<ReturnType<typeof reportFeed>>>
    
    export type ReportFeedMutationError = Blob

    /**
 * @summary 피드 신고
 */
export const useReportFeed = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reportFeed>>, TError,{feedId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reportFeed>>,
        TError,
        {feedId: number},
        TContext
      > => {
      return useMutation(getReportFeedMutationOptions(options), queryClient);
    }
    /**
 * 본인이 작성한 피드를 삭제합니다.
 * @summary 피드 삭제
 */
export type deleteFeedResponse200 = {
  data: Blob
  status: 200
}

export type deleteFeedResponse401 = {
  data: Blob
  status: 401
}

export type deleteFeedResponse403 = {
  data: Blob
  status: 403
}

export type deleteFeedResponse404 = {
  data: Blob
  status: 404
}
    
export type deleteFeedResponseSuccess = (deleteFeedResponse200) & {
  headers: Headers;
};
export type deleteFeedResponseError = (deleteFeedResponse401 | deleteFeedResponse403 | deleteFeedResponse404) & {
  headers: Headers;
};

export type deleteFeedResponse = (deleteFeedResponseSuccess | deleteFeedResponseError)

export const getDeleteFeedUrl = (feedId: number,) => {


  

  return `/api/v1/feeds/${feedId}`
}

export const deleteFeed = async (feedId: number, options?: RequestInit): Promise<deleteFeedResponse> => {
  
  return customFetch<deleteFeedResponse>(getDeleteFeedUrl(feedId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteFeedMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFeed>>, TError,{feedId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteFeed>>, TError,{feedId: number}, TContext> => {

const mutationKey = ['deleteFeed'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteFeed>>, {feedId: number}> = (props) => {
          const {feedId} = props ?? {};

          return  deleteFeed(feedId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteFeedMutationResult = NonNullable<Awaited<ReturnType<typeof deleteFeed>>>
    
    export type DeleteFeedMutationError = Blob

    /**
 * @summary 피드 삭제
 */
export const useDeleteFeed = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFeed>>, TError,{feedId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteFeed>>,
        TError,
        {feedId: number},
        TContext
      > => {
      return useMutation(getDeleteFeedMutationOptions(options), queryClient);
    }
    