/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Sseotdabwa API
 * Sseotdabwa Project
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  VoteRequest
} from '.././model';

import { customFetch } from '.././custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 회원이 피드에 YES/NO 투표합니다. 중복 투표는 불가합니다.
 * @summary 회원 투표
 */
export type voteResponse201 = {
  data: Blob
  status: 201
}

export type voteResponse400 = {
  data: Blob
  status: 400
}

export type voteResponse401 = {
  data: Blob
  status: 401
}

export type voteResponse404 = {
  data: Blob
  status: 404
}
    
export type voteResponseSuccess = (voteResponse201) & {
  headers: Headers;
};
export type voteResponseError = (voteResponse400 | voteResponse401 | voteResponse404) & {
  headers: Headers;
};

export type voteResponse = (voteResponseSuccess | voteResponseError)

export const getVoteUrl = (feedId: number,) => {


  

  return `/api/v1/feeds/${feedId}/votes`
}

export const vote = async (feedId: number,
    voteRequest: VoteRequest, options?: RequestInit): Promise<voteResponse> => {
  
  return customFetch<voteResponse>(getVoteUrl(feedId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      voteRequest,)
  }
);}




export const getVoteMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof vote>>, TError,{feedId: number;data: VoteRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof vote>>, TError,{feedId: number;data: VoteRequest}, TContext> => {

const mutationKey = ['vote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof vote>>, {feedId: number;data: VoteRequest}> = (props) => {
          const {feedId,data} = props ?? {};

          return  vote(feedId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type VoteMutationResult = NonNullable<Awaited<ReturnType<typeof vote>>>
    export type VoteMutationBody = VoteRequest
    export type VoteMutationError = Blob

    /**
 * @summary 회원 투표
 */
export const useVote = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof vote>>, TError,{feedId: number;data: VoteRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof vote>>,
        TError,
        {feedId: number;data: VoteRequest},
        TContext
      > => {
      return useMutation(getVoteMutationOptions(options), queryClient);
    }
    /**
 * 비회원(게스트)이 피드에 YES/NO 투표합니다. 중복 방지는 클라이언트에서 처리합니다.
 * @summary 비회원 투표
 */
export type guestVoteResponse201 = {
  data: Blob
  status: 201
}

export type guestVoteResponse400 = {
  data: Blob
  status: 400
}

export type guestVoteResponse404 = {
  data: Blob
  status: 404
}
    
export type guestVoteResponseSuccess = (guestVoteResponse201) & {
  headers: Headers;
};
export type guestVoteResponseError = (guestVoteResponse400 | guestVoteResponse404) & {
  headers: Headers;
};

export type guestVoteResponse = (guestVoteResponseSuccess | guestVoteResponseError)

export const getGuestVoteUrl = (feedId: number,) => {


  

  return `/api/v1/feeds/${feedId}/votes/guest`
}

export const guestVote = async (feedId: number,
    voteRequest: VoteRequest, options?: RequestInit): Promise<guestVoteResponse> => {
  
  return customFetch<guestVoteResponse>(getGuestVoteUrl(feedId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      voteRequest,)
  }
);}




export const getGuestVoteMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof guestVote>>, TError,{feedId: number;data: VoteRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof guestVote>>, TError,{feedId: number;data: VoteRequest}, TContext> => {

const mutationKey = ['guestVote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof guestVote>>, {feedId: number;data: VoteRequest}> = (props) => {
          const {feedId,data} = props ?? {};

          return  guestVote(feedId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type GuestVoteMutationResult = NonNullable<Awaited<ReturnType<typeof guestVote>>>
    export type GuestVoteMutationBody = VoteRequest
    export type GuestVoteMutationError = Blob

    /**
 * @summary 비회원 투표
 */
export const useGuestVote = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof guestVote>>, TError,{feedId: number;data: VoteRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof guestVote>>,
        TError,
        {feedId: number;data: VoteRequest},
        TContext
      > => {
      return useMutation(getGuestVoteMutationOptions(options), queryClient);
    }
    