/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Sseotdabwa API
 * Sseotdabwa Project
 * OpenAPI spec version: v1.0.0
 */
import type { PresignedPutResponse } from './presignedPutResponse';

export interface ApiResponsePresignedPutResponse {
  data?: PresignedPutResponse;
  message?: string;
  status?: string;
  errorCode?: string;
}
