/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Sseotdabwa API
 * Sseotdabwa Project
 * OpenAPI spec version: v1.0.0
 */
import type { UserWithdrawResponse } from './userWithdrawResponse';

export interface ApiResponseUserWithdrawResponse {
  data?: UserWithdrawResponse;
  message?: string;
  status?: string;
  errorCode?: string;
}
