/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Sseotdabwa API
 * Sseotdabwa Project
 * OpenAPI spec version: v1.0.0
 */
import type { VoteResponse } from './voteResponse';

export interface ApiResponseVoteResponse {
  data?: VoteResponse;
  message?: string;
  status?: string;
  errorCode?: string;
}
