/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Sseotdabwa API
 * Sseotdabwa Project
 * OpenAPI spec version: v1.0.0
 */

/**
 * Apple 소셜 로그인 요청
 */
export interface AppleLoginRequest {
  /** Apple SDK로 발급받은 Authorization Code */
  authorizationCode: string;
  /** Web 로그인 시 사용된 redirect_uri (iOS 네이티브 앱은 생략 가능) */
  redirectUri?: string;
}
