/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Sseotdabwa API
 * Sseotdabwa Project
 * OpenAPI spec version: v1.0.0
 */
import type { FeedResponse } from './feedResponse';

export interface CursorPageResponseFeedResponse {
  content?: FeedResponse[];
  nextCursor?: number;
  hasNext?: boolean;
}
