/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Sseotdabwa API
 * Sseotdabwa Project
 * OpenAPI spec version: v1.0.0
 */
import type { FeedAuthorResponse } from './feedAuthorResponse';
import type { FeedResponseCategory } from './feedResponseCategory';
import type { FeedResponseFeedStatus } from './feedResponseFeedStatus';

export interface FeedResponse {
  feedId?: number;
  content?: string;
  price?: number;
  category?: FeedResponseCategory;
  yesCount?: number;
  noCount?: number;
  feedStatus?: FeedResponseFeedStatus;
  s3ObjectKey?: string;
  imageWidth?: number;
  imageHeight?: number;
  author?: FeedAuthorResponse;
  createdAt?: string;
}
