/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Sseotdabwa API
 * Sseotdabwa Project
 * OpenAPI spec version: v1.0.0
 */

export type FeedResponseFeedStatus = typeof FeedResponseFeedStatus[keyof typeof FeedResponseFeedStatus];


export const FeedResponseFeedStatus = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
} as const;
