/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Sseotdabwa API
 * Sseotdabwa Project
 * OpenAPI spec version: v1.0.0
 */

export type FeedCreateRequestCategory = typeof FeedCreateRequestCategory[keyof typeof FeedCreateRequestCategory];


export const FeedCreateRequestCategory = {
  LUXURY: 'LUXURY',
  FASHION: 'FASHION',
  BEAUTY: 'BEAUTY',
  FOOD: 'FOOD',
  ELECTRONICS: 'ELECTRONICS',
  TRAVEL: 'TRAVEL',
  HEALTH: 'HEALTH',
  BOOK: 'BOOK',
  ETC: 'ETC',
} as const;
