/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Sseotdabwa API
 * Sseotdabwa Project
 * OpenAPI spec version: v1.0.0
 */
import type { FeedCreateRequestCategory } from './feedCreateRequestCategory';

export interface FeedCreateRequest {
  category: FeedCreateRequestCategory;
  price: number;
  /**
   * @minLength 0
   * @maxLength 100
   */
  content?: string;
  s3ObjectKey: string;
  imageWidth: number;
  imageHeight: number;
}
