/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Sseotdabwa API
 * Sseotdabwa Project
 * OpenAPI spec version: v1.0.0
 */

export type GetFeedListFeedStatus = typeof GetFeedListFeedStatus[keyof typeof GetFeedListFeedStatus];


export const GetFeedListFeedStatus = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
} as const;
