/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Sseotdabwa API
 * Sseotdabwa Project
 * OpenAPI spec version: v1.0.0
 */
import type { GetFeedListFeedStatus } from './getFeedListFeedStatus';

export type GetFeedListParams = {
/**
 * 이전 페이지 마지막 feedId (첫 페이지는 생략)
 */
cursor?: number;
/**
 * 페이지 크기 (기본값 20, 최대 50)
 */
size?: number;
/**
 * 피드 상태 필터 (OPEN, CLOSED / 미지정 시 전체)
 */
feedStatus?: GetFeedListFeedStatus;
};
