/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Sseotdabwa API
 * Sseotdabwa Project
 * OpenAPI spec version: v1.0.0
 */
import type { UserResponse } from './userResponse';

export interface TokenResponse {
  accessToken?: string;
  refreshToken?: string;
  tokenType?: string;
  user?: UserResponse;
}
