/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Sseotdabwa API
 * Sseotdabwa Project
 * OpenAPI spec version: v1.0.0
 */

export type UserResponseSocialAccount = typeof UserResponseSocialAccount[keyof typeof UserResponseSocialAccount];


export const UserResponseSocialAccount = {
  KAKAO: 'KAKAO',
  GOOGLE: 'GOOGLE',
  APPLE: 'APPLE',
} as const;
