/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Sseotdabwa API
 * Sseotdabwa Project
 * OpenAPI spec version: v1.0.0
 */
import type { UserResponseSocialAccount } from './userResponseSocialAccount';

export interface UserResponse {
  id?: number;
  nickname?: string;
  profileImage?: string;
  socialAccount?: UserResponseSocialAccount;
}
