/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Sseotdabwa API
 * Sseotdabwa Project
 * OpenAPI spec version: v1.0.0
 */

export type VoteResponseChoice = typeof VoteResponseChoice[keyof typeof VoteResponseChoice];


export const VoteResponseChoice = {
  YES: 'YES',
  NO: 'NO',
} as const;
