/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Sseotdabwa API
 * Sseotdabwa Project
 * OpenAPI spec version: v1.0.0
 */
import type { VoteResponseChoice } from './voteResponseChoice';

export interface VoteResponse {
  feedId?: number;
  choice?: VoteResponseChoice;
  yesCount?: number;
  noCount?: number;
  totalCount?: number;
}
