/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Sseotdabwa API
 * Sseotdabwa Project
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  CreatePresignedPutRequest
} from '.././model';

import { customFetch } from '.././custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 클라이언트(Android/iOS/Web)가 S3에 직접 PUT 업로드할 수 있도록 Presigned URL을 발급합니다.

**동작 흐름**
1) 클라이언트가 파일 메타정보(파일명/확장자 또는 contentType 등)로 Presigned URL 발급 요청
2) 서버가 S3 Object Key 생성 후 Presigned PUT URL(uploadUrl) 발급
3) 클라이언트가 uploadUrl로 S3에 PUT 업로드
4) 클라이언트는 업로드 완료 후, s3ObjectKey를 전달

**중요 정책/주의사항**
- 서버는 파일을 직접 받지 않습니다.
- 클라이언트는 응답받은 uploadUrl로 HTTP PUT 업로드합니다.
- 업로드 시 Content-Type 헤더는 요청의 contentType과 동일해야 합니다.
- viewUrl은 CloudFront public 도메인 기반의 조회 URL이며, 앱에서 이미지 표시 시 사용합니다.

 * @summary Presigned PUT URL 발급
 */
export type createPresignedPutResponse200 = {
  data: Blob
  status: 200
}

export type createPresignedPutResponse400 = {
  data: Blob
  status: 400
}

export type createPresignedPutResponse401 = {
  data: Blob
  status: 401
}

export type createPresignedPutResponse500 = {
  data: Blob
  status: 500
}
    
export type createPresignedPutResponseSuccess = (createPresignedPutResponse200) & {
  headers: Headers;
};
export type createPresignedPutResponseError = (createPresignedPutResponse400 | createPresignedPutResponse401 | createPresignedPutResponse500) & {
  headers: Headers;
};

export type createPresignedPutResponse = (createPresignedPutResponseSuccess | createPresignedPutResponseError)

export const getCreatePresignedPutUrl = () => {


  

  return `/api/v1/uploads/presigned-put`
}

export const createPresignedPut = async (createPresignedPutRequest: CreatePresignedPutRequest, options?: RequestInit): Promise<createPresignedPutResponse> => {
  
  return customFetch<createPresignedPutResponse>(getCreatePresignedPutUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createPresignedPutRequest,)
  }
);}




export const getCreatePresignedPutMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPresignedPut>>, TError,{data: CreatePresignedPutRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createPresignedPut>>, TError,{data: CreatePresignedPutRequest}, TContext> => {

const mutationKey = ['createPresignedPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPresignedPut>>, {data: CreatePresignedPutRequest}> = (props) => {
          const {data} = props ?? {};

          return  createPresignedPut(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePresignedPutMutationResult = NonNullable<Awaited<ReturnType<typeof createPresignedPut>>>
    export type CreatePresignedPutMutationBody = CreatePresignedPutRequest
    export type CreatePresignedPutMutationError = Blob

    /**
 * @summary Presigned PUT URL 발급
 */
export const useCreatePresignedPut = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPresignedPut>>, TError,{data: CreatePresignedPutRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPresignedPut>>,
        TError,
        {data: CreatePresignedPutRequest},
        TContext
      > => {
      return useMutation(getCreatePresignedPutMutationOptions(options), queryClient);
    }
    